version: '3'

# Service configuration.
services:

  # Main drupal application.
  drupal:
    build:
      context: .
      dockerfile: docker/local-dev/drupal/Dockerfile
    volumes:
      - drupal-mount:/var/www/html
    ports:
      - 80
    environment:
      DB_NAME: drupal
      DB_USER: root
      DB_PASS: root
      DB_HOST: mariadb
      ENVIRONMENT: local
      REDIS_CACHE_PREFIX: drupal_
      REDIS_CONNECTION: redis
    networks:
      - default

  # MariaDB SQL database server.
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/local-dev/mariadb/data:/docker-entrypoint-initdb.d
    ports:
      - 3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # Redis key-store database server.
  redis:
    image: redis:6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # Node build container.
  build:
    image: node:15
    volumes:
      - ./web/themes/custom/opwo_theme:/home/node/drupal
    ports:
      - 3000
      - 3001
    working_dir: /home/node/drupal
    command: bash -c "npm install && npm run build-dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # Adminer database management tool.
  adminer:
    image: adminer:latest
    ports:
      - 8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # Mailhog mail catcher.
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025
      - 8025
    environment:
      VIRTUAL_PORT: 8025
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

# Volume definitions.
volumes:
  dbdata:
  drupal-mount:
