version: '3'

# Service configuration.
services:

  # Main drupal application.
  drupal:
    build:
      context: .
      dockerfile: docker/local-dev/drupal/Dockerfile
    volumes:
      - drupal-mount:/var/www/html
    ports:
      - 80
    environment:
      VIRTUAL_HOST: alex-external.dev.localhost
      DB_NAME: drupal
      DB_USER: root
      DB_PASS: root
      DB_HOST: mariadb
      ENVIRONMENT: local
      REDIS_CACHE_PREFIX: drupal_
      REDIS_CONNECTION: redis
    networks:
      - default
      - nginx-proxy

  # MariaDB SQL database server.
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/local-dev/mariadb/data:/docker-entrypoint-initdb.d
    ports:
      - 3306
    networks:
      - default
      - nginx-proxy

  # Redis key-store database server.
  redis:
    image: redis:6
    networks:
      - default
      - nginx-proxy

  # Node build container.
  build:
    image: node:15
    volumes:
      - ./web/themes/custom/opwo_theme:/home/node/drupal
    ports:
      - 3000
      - 3001
    working_dir: /home/node/drupal
    command: bash -c "npm install && npm run build-dev"
    networks:
      - default
      - nginx-proxy

  # Adminer database management tool.
  adminer:
    image: adminer:latest
    ports:
      - 8080
    environment:
      VIRTUAL_HOST: alex-external-adminer.dev.localhost
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - default
      - nginx-proxy

  # Mailhog mail catcher.
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025
      - 8025
    environment:
      VIRTUAL_HOST: alex-external-mailhog.dev.localhost
      VIRTUAL_PORT: 8025
    networks:
      - default
      - nginx-proxy

# Volume definitions.
volumes:
  dbdata:
  drupal-mount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"

# Pull external nginx-proxy network.
networks:
  nginx-proxy:
    external: true
