name: PHP CI

on:
  pull_request:
    branches: [ "main", "uat" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build the Docker
      run: docker compose build

    - name: Run the Docker
      run: docker compose up -d

    - name: Run Behat Tests
      run: docker compose run drupal ./vendor/bin/behat
